### ISSUE TITLE
Reference results for WheelBasedCraneCrab have not been renamed

### ISSUE THREAD

**Issue by arubisch** [DLR-SR/PlanarMechanics_ReferenceResults#1]
The above mentioned model was renamed due to a typo in https://github.com/dzimmer/PlanarMechanics/commit/22d7c542dd215f3474c9b0b64ea5b1770f3b0f68, however, the reference file (and folder) are not adapted accordingly. I would like to change that and have prepared this locally, but apparently am missing writing permissions on this repository.
@tobolar maybe you have insight here :)

**Comment by tobolar** [comment]
> maybe you have insight here :)

I do indeed!

The commit you are referencing to is for the current working version of the library whereas the reference results relate to the lastest [release version v1.5.1](https://github.com/dzimmer/PlanarMechanics/releases/tag/v1.5.1). In this latest release, the example name is stil wrong, but indeed consistent with the reference result name (also wrong).

So IMO no need to change anything at the moment.  
But I make a notice to myself to generate reference results for the next release.

**Comment by arubisch** [comment]
cool, thanks for your quick answer! 
This inconsistency between models and their reference result also explains the behaviour of PlanarMechanics.VehicleComponents.Examples.SingleTrackWithEngine, I suppose -- here I see a deviation in several results from the reference data; I'm using SimulationX.
Do you have any idea, when the next release will come? It will hopefully synchronize models and reference data again :)

**Comment by tobolar** [comment]
Yes, the deviation in `VehicleComponents.Examples.SingleTrackWithEngine` is due to newly added `airResistance`.

A new release? I can do it within several weeks. ;-)

**Comment by tobolar** [comment]
Resolved with PR https://github.com/DLR-SR/PlanarMechanics_ReferenceResults/pull/3
